version: '3.4'

services:
  gponmonitor:
    image: ${DOCKER_REGISTRY}gponmonitor
    restart: always
    volumes:
      - /docker/GPONMonitor/devicesconfiguration.json:/app/devicesconfiguration.json
    ports:
      - "5001:80"
    build:
      context: .
      dockerfile: src/GPONMonitor/Dockerfile
